# Generated by Django 3.0.7 on 2020-06-11 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sign_up', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='name',
        ),
    ]
